import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { colleges } from "@/lib/mock-data";
import { CollegeCard } from "@/components/product/data-ui";
import { FilterPanel, type CollegeFilters } from "@/components/product/filters";
import { EmptyState, PageHeader, Section } from "@/components/product/page";
export const Route=createFileRoute("/colleges/")({head:()=>({meta:[{title:"Discover COMEDK Colleges — COMEDK Compass"},{name:"description",content:"Filter Karnataka engineering colleges by rank, budget, branch, placements and probability."},{property:"og:title",content:"Discover COMEDK Colleges"},{property:"og:description",content:"Find realistic COMEDK college and branch options."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Colleges});
function Colleges(){const [filters,setFilters]=useState<CollegeFilters>({rank:18432,branch:"All branches",budget:300000,location:"All"});const [sort,setSort]=useState("Recommended");const results=useMemo(()=>colleges.filter(c=>(filters.branch==="All branches"||c.branches.includes(filters.branch))&&c.annualFee<=filters.budget&&(filters.location==="All"||c.location.includes(filters.location))).sort((a,b)=>sort==="Fees"?a.annualFee-b.annualFee:sort==="Placement"?b.medianPackage-a.medianPackage:sort==="Cutoff"?a.latestCutoff-b.latestCutoff:b.roi-a.roi),[filters,sort]);return <><PageHeader eyebrow="College discovery" title="Find options that fit your rank." description="Filter by the constraints that matter, then inspect every cutoff, fee and outcome in context."/><Section><div className="mb-5 flex items-center justify-between"><p className="text-sm text-muted-foreground"><strong className="text-foreground">{results.length}</strong> realistic options</p><div className="flex gap-2"><Sheet><SheetTrigger asChild><Button variant="outline" className="lg:hidden"><SlidersHorizontal/>Filters</Button></SheetTrigger><SheetContent side="left" className="w-[330px] p-4"><FilterPanel filters={filters} onChange={setFilters} className="mt-8 border-0 shadow-none"/></SheetContent></Sheet><Select value={sort} onValueChange={setSort}><SelectTrigger className="w-36"><SelectValue/></SelectTrigger><SelectContent>{["Recommended","Cutoff","Fees","Placement","ROI"].map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></div></div><div className="grid gap-6 lg:grid-cols-[240px_1fr]"><FilterPanel filters={filters} onChange={setFilters} className="hidden h-fit lg:block"/><div>{results.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{results.map(c=><CollegeCard key={c.id} college={c}/>)}</div>:<EmptyState title="No colleges match these filters" description="Try raising your budget or choosing another branch." action={<Button variant="outline" onClick={()=>setFilters({rank:18432,branch:"All branches",budget:300000,location:"All"})}>Reset filters</Button>}/>}</div></div></Section></>}
