import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Plus, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { colleges } from "@/lib/mock-data";
import { CollegeLogo } from "@/components/product/brand";
import { VerificationBadge } from "@/components/product/data-ui";
import { DataNotice } from "@/components/product/data-ui";
import { PageHeader, Panel, Section } from "@/components/product/page";
export const Route=createFileRoute("/compare")({head:()=>({meta:[{title:"Compare COMEDK Colleges — COMEDK Compass"},{name:"description",content:"Compare admission cutoffs, fees, placements, ROI and verified data across COMEDK colleges."},{property:"og:title",content:"Compare COMEDK Colleges"},{property:"og:description",content:"A clear side-by-side college comparison."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Compare});
const metrics=[{label:"CSE closing rank",key:"latestCutoff",format:(v:number)=>v.toLocaleString("en-IN"),lower:true},{label:"Annual fee",key:"annualFee",format:(v:number)=>`₹${(v/100000).toFixed(1)}L`,lower:true},{label:"Hostel estimate",key:"hostelFee",format:(v:number)=>`₹${(v/100000).toFixed(1)}L`,lower:true},{label:"Median package",key:"medianPackage",format:(v:number)=>`₹${(v/100000).toFixed(1)} LPA`},{label:"ROI score",key:"roi",format:(v:number)=>`${v}/10`} ] as const;
function Compare(){const [ids,setIds]=useState(["rvce","bmsce","rnsit"]);const selected=ids.map(id=>colleges.find(c=>c.id===id)).filter((c):c is (typeof colleges)[number]=>Boolean(c));const update=(i:number,id:string)=>setIds(old=>old.map((v,n)=>n===i?id:v));return <><PageHeader eyebrow="College comparison" title="Compare outcomes, not reputations." description="Admission difficulty, cost and placement outcomes belong in the same decision."/><Section><DataNotice>All values are demo data labeled with their source year. Verify current fees and official cutoffs before choice filling.</DataNotice><div className="mt-6 overflow-x-auto"><div className="min-w-[760px]"><div className="sticky top-16 z-20 grid grid-cols-[180px_repeat(3,1fr)] border-b border-border bg-background py-4"><div className="self-end text-xs font-semibold text-muted-foreground">Metric</div>{selected.map((c,i)=><div className="px-4" key={c.id}><div className="flex items-center gap-3"><CollegeLogo initials={c.accent}/><div className="min-w-0"><strong>{c.shortName}</strong><p className="truncate text-xs text-muted-foreground">{c.location}</p></div></div><Select value={c.id} onValueChange={id=>update(i,id)}><SelectTrigger className="mt-3 h-8"><SelectValue/></SelectTrigger><SelectContent>{colleges.map(x=><SelectItem value={x.id} key={x.id}>{x.shortName}</SelectItem>)}</SelectContent></Select></div>)}</div><Panel className="overflow-hidden rounded-t-none">{metrics.map(metric=>{const vals=selected.map(c=>Number(c[metric.key]));const best=metric.lower?Math.min(...vals):Math.max(...vals);return <div key={metric.key} className="grid grid-cols-[180px_repeat(3,1fr)] border-b border-border last:border-0"><div className="p-4 text-sm text-muted-foreground">{metric.label}</div>{selected.map(c=>{const value=Number(c[metric.key]);const max=Math.max(...vals);return <div className="border-l border-border p-4" key={c.id}><strong className={value===best?"text-primary":""}>{metric.format(value)}</strong><div className="mt-3 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${Math.max(12,(value/max)*100)}%`}}/></div></div>})}</div>})}<div className="grid grid-cols-[180px_repeat(3,1fr)]"><div className="p-4 text-sm text-muted-foreground">Verified data</div>{selected.map(c=><div className="border-l border-border p-4" key={c.id}>{c.verified?<VerificationBadge/>:<span className="text-xs text-muted-foreground">Institution only</span>}</div>)}</div></Panel></div></div></Section></>}
