import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CalendarClock, Flag, ShieldCheck, Target } from "lucide-react";
import { Button } from "@/components/ui/button";
import { colleges, counselling } from "@/lib/mock-data";
import { CollegeLogo } from "@/components/product/brand";
import { ProbabilityTimeline } from "@/components/product/data-ui";
import { PageHeader, Panel, Section, SectionHeading } from "@/components/product/page";
export const Route=createFileRoute("/counselling")({head:()=>({meta:[{title:"COMEDK Counselling 2026 — COMEDK Compass"},{name:"description",content:"Plan each COMEDK counselling round with safe, target and reach options."},{property:"og:title",content:"COMEDK Counselling 2026"},{property:"og:description",content:"Your round-wise counselling mission control."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Counselling});
function Counselling(){const groups=[{title:"Safe",icon:ShieldCheck,color:"text-positive",colleges:colleges.slice(4,6),values:[[45,64,82,91],[51,70,86,94]]},{title:"Target",icon:Target,color:"text-warning",colleges:colleges.slice(3,5),values:[[16,35,61,76],[12,27,61,78]]},{title:"Reach",icon:Flag,color:"text-info",colleges:colleges.slice(1,3),values:[[3,8,18,27],[2,6,13,21]]}];return <><PageHeader eyebrow="Mission control" title="COMEDK Counselling 2026" description="A round-aware strategy built around rank 18,432, preferred branches and an ₹8L total budget." actions={<Button asChild><Link to="/preference-list">Build preference list <ArrowRight/></Link></Button>}/><Section><div className="grid gap-4 lg:grid-cols-[.75fr_1.25fr]"><Panel className="bg-foreground p-6 text-background"><div className="flex items-center justify-between"><span className="font-mono text-xs uppercase">Current phase</span><span className="rounded-full bg-positive/20 px-2 py-1 text-[10px] font-semibold text-positive">Active</span></div><strong className="mt-5 block text-4xl">{counselling.phase}</strong><p className="mt-2 text-sm text-background/60">Choice editing remains open.</p></Panel><Panel className="p-6"><div className="flex gap-4"><span className="grid size-10 place-items-center rounded-md bg-warning/10 text-warning"><CalendarClock className="size-5"/></span><div><p className="text-xs text-muted-foreground">Next important event</p><h2 className="mt-1 text-xl font-semibold">{counselling.nextEvent}</h2><p className="mt-2 font-mono text-sm text-primary">{counselling.nextEventDate}</p></div></div></Panel></div><SectionHeading eyebrow="Your counselling strategy" title="Balance ambition with coverage." description="Probabilities reflect historical round movement and are estimates, never guarantees."/><div className="grid gap-5 lg:grid-cols-3">{groups.map(group=><Panel className="overflow-hidden" key={group.title}><div className="flex items-center gap-2 border-b border-border p-4"><group.icon className={`size-4 ${group.color}`}/><strong>{group.title}</strong><span className="ml-auto text-xs text-muted-foreground">{group.colleges.length} options</span></div><div className="divide-y divide-border">{group.colleges.map((c,i)=><div className="p-4" key={c.id}><div className="flex items-center gap-3"><CollegeLogo initials={c.accent} className="size-9"/><div><strong className="text-sm">{c.shortName} · {i?"AIML":"CSE"}</strong><p className="text-[11px] text-muted-foreground">Cutoff {c.latestCutoff.toLocaleString("en-IN")} · movement +{8+i*3}%</p></div></div><div className="mt-4"><ProbabilityTimeline rounds={group.values[i] ?? [0,0,0,0]} compact/></div></div>)}</div></Panel>)}</div></Section></>}
