import { createFileRoute, Link } from "@tanstack/react-router";
import { Fragment, useState } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { colleges, cutoffs, rnsitTrends } from "@/lib/mock-data";
import { SourceBadge, TrendChart, TrendDelta } from "@/components/product/data-ui";
import { PageHeader, Panel, Section } from "@/components/product/page";
export const Route=createFileRoute("/cutoffs")({head:()=>({meta:[{title:"COMEDK Cutoff Explorer — COMEDK Compass"},{name:"description",content:"Explore round-wise COMEDK engineering cutoffs by college, branch, year and category."},{property:"og:title",content:"COMEDK Cutoff Explorer"},{property:"og:description",content:"Round-by-round cutoff intelligence for Karnataka colleges."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Cutoffs});
function Cutoffs(){const [branch,setBranch]=useState("All");const [open,setOpen]=useState<string|null>("rnsit");const rows=cutoffs.filter(x=>branch==="All"||x.branch===branch);return <><PageHeader eyebrow="Cutoff explorer" title="Read the movement between rounds." description="Use official historical data to understand how branches actually move through counselling."/><Section><Panel className="mb-5 flex flex-wrap gap-3 p-4"><Select defaultValue="2025"><SelectTrigger className="w-28"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="2025">2025</SelectItem><SelectItem value="2024">2024</SelectItem></SelectContent></Select><Select value={branch} onValueChange={setBranch}><SelectTrigger className="w-36"><SelectValue/></SelectTrigger><SelectContent>{["All","CSE","AIML","ISE","ECE"].map(v=><SelectItem value={v} key={v}>{v==="All"?"All branches":v}</SelectItem>)}</SelectContent></Select><Button variant="outline">GM category</Button><span className="ml-auto self-center text-xs text-muted-foreground">Demo dataset · {rows.length} records</span></Panel><div className="overflow-x-auto rounded-lg border border-border bg-card"><table className="w-full min-w-[820px] text-sm"><thead className="bg-muted/60 text-left text-xs text-muted-foreground"><tr>{["College","Branch","Round 1","Round 2","Round 3","Round 4","Trend",""].map((h,i)=><th key={i} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{rows.map(row=>{const c=colleges.find(x=>x.id===row.collegeId);const expanded=open===row.collegeId;return <Fragment key={`${row.collegeId}-${row.branch}`}><tr className="border-t border-border hover:bg-muted/30"><td className="px-4 py-4"><Link to="/colleges/$slug" params={{slug:c?.slug??""}} className="font-semibold hover:text-primary">{c?.shortName}</Link></td><td className="px-4 py-4">{row.branch}</td>{row.rounds.map(n=><td key={n} className="px-4 py-4 font-mono">{n.toLocaleString("en-IN")}</td>)}<td className="px-4 py-4"><TrendDelta value={8}/></td><td className="px-4 py-4"><Button variant="ghost" size="icon" onClick={()=>setOpen(expanded?null:row.collegeId)} aria-label="View historical details">{expanded?<ChevronUp/>:<ChevronDown/>}</Button></td></tr>{expanded&&<tr key={`${row.collegeId}-detail`} className="border-t border-border bg-muted/20"><td colSpan={8} className="p-5"><div className="grid gap-5 lg:grid-cols-[1fr_200px]"><TrendChart values={rnsitTrends.CSE.map(v=>Math.round(v*(row.rounds[3]/19120)))} height={170}/><div><p className="text-sm font-semibold">Historical context</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Closing rank expanded consistently after Round 2 across the last four counselling cycles.</p><div className="mt-4"><SourceBadge meta={row.source}/></div></div></div></td></tr>}</Fragment>})}</tbody></table></div></Section></>}
