import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Building2, Flag, ListChecks, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { colleges, probabilities } from "@/lib/mock-data";
import { CollegeLogo } from "@/components/product/brand";
import { ProbabilityBadge, ProbabilityTimeline } from "@/components/product/data-ui";
import { PageHeader, Panel, Section, SectionHeading } from "@/components/product/page";
export const Route=createFileRoute("/dashboard")({head:()=>({meta:[{title:"My Counselling Dashboard — COMEDK Compass"},{name:"description",content:"Your personalized COMEDK counselling command center."},{property:"og:title",content:"My Counselling Dashboard — COMEDK Compass"},{property:"og:description",content:"Track matches, rounds, and next counselling actions."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Dashboard});
function Dashboard(){return <><PageHeader eyebrow="Personal command center" title="Good morning, Student" description="Your shortlist and strategy are calibrated for COMEDK rank 18,432." actions={<Button asChild><Link to="/preference-list">Open preference list <ArrowRight/></Link></Button>}/><Section><Panel className="grid gap-6 p-5 sm:grid-cols-3"><Profile label="COMEDK rank" value="18,432"/><Profile label="Preferred branches" value="CSE · AIML · ISE"/><Profile label="Total budget" value="₹4L–₹8L"/></Panel><SectionHeading eyebrow="Admission overview" title="Your option landscape"/><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Possible colleges","12",Building2],["Strong matches","4",ShieldCheck],["Reach colleges","3",Flag],["Safe options","5",ListChecks]].map(([l,v,I])=><Panel className="p-5" key={String(l)}><I className="size-4 text-primary"/><strong className="mt-5 block text-3xl">{v}</strong><span className="text-sm text-muted-foreground">{l}</span></Panel>)}</div><div className="mt-12 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><div><SectionHeading title="Your shortlist" description="Estimated against the current round and your saved preferences."/><div className="space-y-3">{colleges.slice(3,6).map((c,i)=><Panel className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center" key={c.id}><CollegeLogo initials={c.accent}/><div className="min-w-0 flex-1"><strong className="block truncate">{c.name}</strong><span className="text-xs text-muted-foreground">{["ISE","CSE","AIML"][i]} · latest cutoff {c.latestCutoff.toLocaleString("en-IN")}</span></div><ProbabilityBadge chance={c.chance} value={[63,78,84][i]}/><Link to="/colleges/$slug" params={{slug:c.slug}} className="text-sm font-semibold text-primary">Details →</Link></Panel>)}</div></div><div><SectionHeading title="Counselling timeline"/><Panel className="p-5"><ProbabilityTimeline rounds={[12,27,61,78]}/><div className="mt-7 border-t border-border pt-5"><p className="text-sm font-semibold">Round 3 results are approaching.</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Three shortlisted colleges historically see significant movement in this round.</p><Button variant="outline" className="mt-4 w-full" asChild><Link to="/counselling">View round trends</Link></Button></div></Panel></div></div></Section></>}
function Profile({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 font-mono text-lg font-semibold">{value}</p></div>}
