import type { College } from "./types";
export const colleges: College[] = [
  { id:"rvce",slug:"rv-college-of-engineering",shortName:"RVCE",name:"R.V. College of Engineering",location:"Mysuru Road, Bengaluru",type:"Autonomous",established:1963,branches:["CSE","AIML","ISE","ECE"],latestCutoff:1842,annualFee:290000,hostelFee:125000,medianPackage:1620000,roi:9.1,chance:"Low",verified:true,accent:"RV" },
  { id:"bmsce",slug:"bms-college-of-engineering",shortName:"BMSCE",name:"B.M.S. College of Engineering",location:"Basavanagudi, Bengaluru",type:"Autonomous",established:1946,branches:["CSE","AIML","ISE","ECE"],latestCutoff:4721,annualFee:270000,hostelFee:110000,medianPackage:1180000,roi:7.8,chance:"Reach",verified:true,accent:"BM" },
  { id:"msrit",slug:"ramaiah-institute-of-technology",shortName:"MSRIT",name:"Ramaiah Institute of Technology",location:"Mathikere, Bengaluru",type:"Autonomous",established:1962,branches:["CSE","AIML","ISE","ECE","EEE"],latestCutoff:6230,annualFee:280000,hostelFee:120000,medianPackage:980000,roi:6.9,chance:"Reach",verified:true,accent:"MR" },
  { id:"dsce",slug:"dayananda-sagar-college-of-engineering",shortName:"DSCE",name:"Dayananda Sagar College of Engineering",location:"Kumaraswamy Layout, Bengaluru",type:"Autonomous",established:1979,branches:["CSE","AIML","ISE","ECE"],latestCutoff:12860,annualFee:260000,hostelFee:115000,medianPackage:720000,roi:5.6,chance:"Possible",verified:true,accent:"DS" },
  { id:"rnsit",slug:"rns-institute-of-technology",shortName:"RNSIT",name:"RNS Institute of Technology",location:"Rajarajeshwari Nagar, Bengaluru",type:"Autonomous",established:2001,branches:["CSE","AIML","ISE","ECE","EEE"],latestCutoff:19120,annualFee:255000,hostelFee:105000,medianPackage:850000,roi:6.2,chance:"Strong",verified:true,accent:"RN" },
  { id:"bmsit",slug:"bms-institute-of-technology",shortName:"BMSIT",name:"BMS Institute of Technology",location:"Yelahanka, Bengaluru",type:"Autonomous",established:2002,branches:["CSE","AIML","ISE","ECE"],latestCutoff:21540,annualFee:250000,hostelFee:98000,medianPackage:760000,roi:5.9,chance:"Strong",verified:true,accent:"BI" },
  { id:"nie",slug:"national-institute-of-engineering",shortName:"NIE",name:"The National Institute of Engineering",location:"Mysuru, Karnataka",type:"Autonomous",established:1946,branches:["CSE","AIML","ISE","ECE"],latestCutoff:17240,annualFee:245000,hostelFee:90000,medianPackage:820000,roi:6.8,chance:"Possible",verified:true,accent:"NI" },
  { id:"jss",slug:"jss-science-and-technology-university",shortName:"JSSSTU",name:"JSS Science and Technology University",location:"Mysuru, Karnataka",type:"Private",established:1963,branches:["CSE","ISE","ECE","EEE"],latestCutoff:14310,annualFee:250000,hostelFee:95000,medianPackage:790000,roi:6.3,chance:"Possible",verified:false,accent:"JS" },
];
export const getCollege = (slug: string) => colleges.find((college) => college.slug === slug);
