"""initial_comedk_data_foundation_schema

Revision ID: 48219ca4aa58
Revises: 
Create Date: 2026-09-28 23:27:38.473734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48219ca4aa58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=True)
    op.create_index(op.f('ix_branches_name'), 'branches', ['name'], unique=False)
    op.create_table('categories',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_code'), 'categories', ['code'], unique=True)
    op.create_table('colleges',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colleges_code'), 'colleges', ['code'], unique=True)
    op.create_index(op.f('ix_colleges_location'), 'colleges', ['location'], unique=False)
    op.create_index(op.f('ix_colleges_name'), 'colleges', ['name'], unique=False)
    op.create_table('counselling_rounds',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_counselling_rounds_year_code', 'counselling_rounds', ['academic_year', 'code'], unique=True)
    op.create_index(op.f('ix_counselling_rounds_academic_year'), 'counselling_rounds', ['academic_year'], unique=False)
    op.create_index(op.f('ix_counselling_rounds_code'), 'counselling_rounds', ['code'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('downloaded_count', sa.Integer(), nullable=False),
    sa.Column('parsed_count', sa.Integer(), nullable=False),
    sa.Column('published_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('needs_review_count', sa.Integer(), nullable=False),
    sa.Column('validation_error_count', sa.Integer(), nullable=False),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_academic_year'), 'sources', ['academic_year'], unique=False)
    op.create_index(op.f('ix_sources_document_type'), 'sources', ['document_type'], unique=False)
    op.create_index(op.f('ix_sources_url'), 'sources', ['url'], unique=True)
    op.create_table('college_aliases',
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_college_aliases_college_alias', 'college_aliases', ['college_id', 'alias'], unique=True)
    op.create_index(op.f('ix_college_aliases_alias'), 'college_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_college_aliases_college_id'), 'college_aliases', ['college_id'], unique=False)
    op.create_table('source_versions',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('source_title', sa.String(length=512), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('counselling_round', sa.String(length=50), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('local_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_versions_source_hash', 'source_versions', ['source_id', 'content_hash'], unique=False)
    op.create_index('idx_source_versions_year_round', 'source_versions', ['academic_year', 'counselling_round'], unique=False)
    op.create_index(op.f('ix_source_versions_academic_year'), 'source_versions', ['academic_year'], unique=False)
    op.create_index(op.f('ix_source_versions_content_hash'), 'source_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_versions_counselling_round'), 'source_versions', ['counselling_round'], unique=False)
    op.create_index(op.f('ix_source_versions_document_type'), 'source_versions', ['document_type'], unique=False)
    op.create_index(op.f('ix_source_versions_ingestion_run_id'), 'source_versions', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_source_versions_processing_status'), 'source_versions', ['processing_status'], unique=False)
    op.create_index(op.f('ix_source_versions_source_id'), 'source_versions', ['source_id'], unique=False)
    op.create_table('college_branches',
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('source_version_id', sa.UUID(), nullable=True),
    sa.Column('course_code', sa.String(length=50), nullable=True),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_college_branch_year', 'college_branches', ['college_id', 'branch_id', 'academic_year'], unique=True)
    op.create_index(op.f('ix_college_branches_academic_year'), 'college_branches', ['academic_year'], unique=False)
    op.create_index(op.f('ix_college_branches_branch_id'), 'college_branches', ['branch_id'], unique=False)
    op.create_index(op.f('ix_college_branches_college_id'), 'college_branches', ['college_id'], unique=False)
    op.create_table('cutoff_records',
    sa.Column('source_version_id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('opening_rank', sa.Integer(), nullable=True),
    sa.Column('closing_rank', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('row_identifier', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('closing_rank > 0', name='chk_cutoff_closing_rank_positive'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['counselling_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cutoff_filter_lookup', 'cutoff_records', ['academic_year', 'round_id', 'status'], unique=False)
    op.create_index('idx_cutoff_unique_logical_record', 'cutoff_records', ['college_id', 'branch_id', 'category_id', 'round_id', 'academic_year', 'source_version_id'], unique=True)
    op.create_index(op.f('ix_cutoff_records_academic_year'), 'cutoff_records', ['academic_year'], unique=False)
    op.create_index(op.f('ix_cutoff_records_branch_id'), 'cutoff_records', ['branch_id'], unique=False)
    op.create_index(op.f('ix_cutoff_records_category_id'), 'cutoff_records', ['category_id'], unique=False)
    op.create_index(op.f('ix_cutoff_records_closing_rank'), 'cutoff_records', ['closing_rank'], unique=False)
    op.create_index(op.f('ix_cutoff_records_college_id'), 'cutoff_records', ['college_id'], unique=False)
    op.create_index(op.f('ix_cutoff_records_round_id'), 'cutoff_records', ['round_id'], unique=False)
    op.create_index(op.f('ix_cutoff_records_source_version_id'), 'cutoff_records', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_cutoff_records_status'), 'cutoff_records', ['status'], unique=False)
    op.create_table('fee_records',
    sa.Column('source_version_id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('total_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tuition_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fee_records_lookup', 'fee_records', ['academic_year', 'college_id', 'status'], unique=False)
    op.create_index(op.f('ix_fee_records_academic_year'), 'fee_records', ['academic_year'], unique=False)
    op.create_index(op.f('ix_fee_records_branch_id'), 'fee_records', ['branch_id'], unique=False)
    op.create_index(op.f('ix_fee_records_college_id'), 'fee_records', ['college_id'], unique=False)
    op.create_index(op.f('ix_fee_records_source_version_id'), 'fee_records', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_fee_records_status'), 'fee_records', ['status'], unique=False)
    op.create_table('seat_records',
    sa.Column('source_version_id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('round_id', sa.UUID(), nullable=True),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('vacant_seats', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['counselling_rounds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_seat_records_lookup', 'seat_records', ['academic_year', 'college_id', 'branch_id', 'status'], unique=False)
    op.create_index(op.f('ix_seat_records_academic_year'), 'seat_records', ['academic_year'], unique=False)
    op.create_index(op.f('ix_seat_records_branch_id'), 'seat_records', ['branch_id'], unique=False)
    op.create_index(op.f('ix_seat_records_category_id'), 'seat_records', ['category_id'], unique=False)
    op.create_index(op.f('ix_seat_records_college_id'), 'seat_records', ['college_id'], unique=False)
    op.create_index(op.f('ix_seat_records_round_id'), 'seat_records', ['round_id'], unique=False)
    op.create_index(op.f('ix_seat_records_source_version_id'), 'seat_records', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_seat_records_status'), 'seat_records', ['status'], unique=False)
    op.create_table('validation_errors',
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('source_version_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_identifier', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_validation_errors_run_code', 'validation_errors', ['ingestion_run_id', 'error_code'], unique=False)
    op.create_index(op.f('ix_validation_errors_entity_identifier'), 'validation_errors', ['entity_identifier'], unique=False)
    op.create_index(op.f('ix_validation_errors_entity_type'), 'validation_errors', ['entity_type'], unique=False)
    op.create_index(op.f('ix_validation_errors_error_code'), 'validation_errors', ['error_code'], unique=False)
    op.create_index(op.f('ix_validation_errors_ingestion_run_id'), 'validation_errors', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_validation_errors_severity'), 'validation_errors', ['severity'], unique=False)
    op.create_index(op.f('ix_validation_errors_source_version_id'), 'validation_errors', ['source_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_errors_source_version_id'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_severity'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_ingestion_run_id'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_error_code'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_entity_type'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_entity_identifier'), table_name='validation_errors')
    op.drop_index('idx_validation_errors_run_code', table_name='validation_errors')
    op.drop_table('validation_errors')
    op.drop_index(op.f('ix_seat_records_status'), table_name='seat_records')
    op.drop_index(op.f('ix_seat_records_source_version_id'), table_name='seat_records')
    op.drop_index(op.f('ix_seat_records_round_id'), table_name='seat_records')
    op.drop_index(op.f('ix_seat_records_college_id'), table_name='seat_records')
    op.drop_index(op.f('ix_seat_records_category_id'), table_name='seat_records')
    op.drop_index(op.f('ix_seat_records_branch_id'), table_name='seat_records')
    op.drop_index(op.f('ix_seat_records_academic_year'), table_name='seat_records')
    op.drop_index('idx_seat_records_lookup', table_name='seat_records')
    op.drop_table('seat_records')
    op.drop_index(op.f('ix_fee_records_status'), table_name='fee_records')
    op.drop_index(op.f('ix_fee_records_source_version_id'), table_name='fee_records')
    op.drop_index(op.f('ix_fee_records_college_id'), table_name='fee_records')
    op.drop_index(op.f('ix_fee_records_branch_id'), table_name='fee_records')
    op.drop_index(op.f('ix_fee_records_academic_year'), table_name='fee_records')
    op.drop_index('idx_fee_records_lookup', table_name='fee_records')
    op.drop_table('fee_records')
    op.drop_index(op.f('ix_cutoff_records_status'), table_name='cutoff_records')
    op.drop_index(op.f('ix_cutoff_records_source_version_id'), table_name='cutoff_records')
    op.drop_index(op.f('ix_cutoff_records_round_id'), table_name='cutoff_records')
    op.drop_index(op.f('ix_cutoff_records_college_id'), table_name='cutoff_records')
    op.drop_index(op.f('ix_cutoff_records_closing_rank'), table_name='cutoff_records')
    op.drop_index(op.f('ix_cutoff_records_category_id'), table_name='cutoff_records')
    op.drop_index(op.f('ix_cutoff_records_branch_id'), table_name='cutoff_records')
    op.drop_index(op.f('ix_cutoff_records_academic_year'), table_name='cutoff_records')
    op.drop_index('idx_cutoff_unique_logical_record', table_name='cutoff_records')
    op.drop_index('idx_cutoff_filter_lookup', table_name='cutoff_records')
    op.drop_table('cutoff_records')
    op.drop_index(op.f('ix_college_branches_college_id'), table_name='college_branches')
    op.drop_index(op.f('ix_college_branches_branch_id'), table_name='college_branches')
    op.drop_index(op.f('ix_college_branches_academic_year'), table_name='college_branches')
    op.drop_index('idx_college_branch_year', table_name='college_branches')
    op.drop_table('college_branches')
    op.drop_index(op.f('ix_source_versions_source_id'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_processing_status'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_ingestion_run_id'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_document_type'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_counselling_round'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_content_hash'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_academic_year'), table_name='source_versions')
    op.drop_index('idx_source_versions_year_round', table_name='source_versions')
    op.drop_index('idx_source_versions_source_hash', table_name='source_versions')
    op.drop_table('source_versions')
    op.drop_index(op.f('ix_college_aliases_college_id'), table_name='college_aliases')
    op.drop_index(op.f('ix_college_aliases_alias'), table_name='college_aliases')
    op.drop_index('idx_college_aliases_college_alias', table_name='college_aliases')
    op.drop_table('college_aliases')
    op.drop_index(op.f('ix_sources_url'), table_name='sources')
    op.drop_index(op.f('ix_sources_document_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_academic_year'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_counselling_rounds_code'), table_name='counselling_rounds')
    op.drop_index(op.f('ix_counselling_rounds_academic_year'), table_name='counselling_rounds')
    op.drop_index('idx_counselling_rounds_year_code', table_name='counselling_rounds')
    op.drop_table('counselling_rounds')
    op.drop_index(op.f('ix_colleges_name'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_location'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_code'), table_name='colleges')
    op.drop_table('colleges')
    op.drop_index(op.f('ix_categories_code'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_branches_name'), table_name='branches')
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
