"""add_source_registry_and_ingestion_review_queue

Revision ID: 5f20cbd3e7fc
Revises: 66d0413043b3
Create Date: 2026-09-29 19:16:26.804752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f20cbd3e7fc'
down_revision: Union[str, Sequence[str], None] = '66d0413043b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_review_items',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_version_id', sa.UUID(), nullable=True),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_url', sa.String(length=1024), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('review_notes', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_items_status_reason', 'ingestion_review_items', ['status', 'failure_reason'], unique=False)
    op.create_index(op.f('ix_ingestion_review_items_document_type'), 'ingestion_review_items', ['document_type'], unique=False)
    op.create_index(op.f('ix_ingestion_review_items_failure_reason'), 'ingestion_review_items', ['failure_reason'], unique=False)
    op.create_index(op.f('ix_ingestion_review_items_ingestion_run_id'), 'ingestion_review_items', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_ingestion_review_items_source_id'), 'ingestion_review_items', ['source_id'], unique=False)
    op.create_index(op.f('ix_ingestion_review_items_source_version_id'), 'ingestion_review_items', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_ingestion_review_items_status'), 'ingestion_review_items', ['status'], unique=False)
    op.create_index(op.f('ix_colleges_institution_type'), 'colleges', ['institution_type'], unique=False)
    op.add_column('sources', sa.Column('source_code', sa.String(length=100), nullable=True))
    op.add_column('sources', sa.Column('source_type', sa.String(length=50), nullable=False, server_default='OFFICIAL_PORTAL'))
    op.add_column('sources', sa.Column('authority_level', sa.String(length=50), nullable=False, server_default='OFFICIAL_PRIMARY'))
    op.add_column('sources', sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('sources', sa.Column('check_frequency_hours', sa.Integer(), nullable=False, server_default='24'))
    op.add_column('sources', sa.Column('expected_document_types', sa.JSON(), nullable=True))
    op.add_column('sources', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sources', sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sources', sa.Column('last_seen_hash', sa.String(length=64), nullable=True))
    op.add_column('sources', sa.Column('parser_type', sa.String(length=50), nullable=True))
    op.add_column('sources', sa.Column('parser_version', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_sources_source_code'), 'sources', ['source_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_source_code'), table_name='sources')
    op.drop_column('sources', 'parser_version')
    op.drop_column('sources', 'parser_type')
    op.drop_column('sources', 'last_seen_hash')
    op.drop_column('sources', 'last_success_at')
    op.drop_column('sources', 'last_checked_at')
    op.drop_column('sources', 'expected_document_types')
    op.drop_column('sources', 'check_frequency_hours')
    op.drop_column('sources', 'is_enabled')
    op.drop_column('sources', 'authority_level')
    op.drop_column('sources', 'source_type')
    op.drop_column('sources', 'source_code')
    op.drop_index(op.f('ix_colleges_institution_type'), table_name='colleges')
    op.drop_index(op.f('ix_ingestion_review_items_status'), table_name='ingestion_review_items')
    op.drop_index(op.f('ix_ingestion_review_items_source_version_id'), table_name='ingestion_review_items')
    op.drop_index(op.f('ix_ingestion_review_items_source_id'), table_name='ingestion_review_items')
    op.drop_index(op.f('ix_ingestion_review_items_ingestion_run_id'), table_name='ingestion_review_items')
    op.drop_index(op.f('ix_ingestion_review_items_failure_reason'), table_name='ingestion_review_items')
    op.drop_index(op.f('ix_ingestion_review_items_document_type'), table_name='ingestion_review_items')
    op.drop_index('idx_review_items_status_reason', table_name='ingestion_review_items')
    op.drop_table('ingestion_review_items')
    # ### end Alembic commands ###
