/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as CutoffsRouteImport } from './routes/cutoffs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as CollegesIndexRouteImport } from './routes/colleges.index'
import { Route as CollegesSlugRouteImport } from './routes/colleges.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const CutoffsRoute = CutoffsRouteImport.update({
  id: '/cutoffs',
  path: '/cutoffs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesIndexRoute = CollegesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollegesRoute,
} as any)
const CollegesSlugRoute = CollegesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollegesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colleges': typeof CollegesRouteWithChildren
  '/cutoffs': typeof CutoffsRoute
  '/dashboard': typeof DashboardRoute
  '/predictor': typeof PredictorRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/colleges/': typeof CollegesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cutoffs': typeof CutoffsRoute
  '/dashboard': typeof DashboardRoute
  '/predictor': typeof PredictorRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/colleges': typeof CollegesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colleges': typeof CollegesRouteWithChildren
  '/cutoffs': typeof CutoffsRoute
  '/dashboard': typeof DashboardRoute
  '/predictor': typeof PredictorRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/colleges/': typeof CollegesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colleges'
    | '/cutoffs'
    | '/dashboard'
    | '/predictor'
    | '/colleges/$slug'
    | '/colleges/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cutoffs'
    | '/dashboard'
    | '/predictor'
    | '/colleges/$slug'
    | '/colleges'
  id:
    | '__root__'
    | '/'
    | '/colleges'
    | '/cutoffs'
    | '/dashboard'
    | '/predictor'
    | '/colleges/$slug'
    | '/colleges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollegesRoute: typeof CollegesRouteWithChildren
  CutoffsRoute: typeof CutoffsRoute
  DashboardRoute: typeof DashboardRoute
  PredictorRoute: typeof PredictorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cutoffs': {
      id: '/cutoffs'
      path: '/cutoffs'
      fullPath: '/cutoffs'
      preLoaderRoute: typeof CutoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/': {
      id: '/colleges/'
      path: '/'
      fullPath: '/colleges/'
      preLoaderRoute: typeof CollegesIndexRouteImport
      parentRoute: typeof CollegesRoute
    }
    '/colleges/$slug': {
      id: '/colleges/$slug'
      path: '/$slug'
      fullPath: '/colleges/$slug'
      preLoaderRoute: typeof CollegesSlugRouteImport
      parentRoute: typeof CollegesRoute
    }
  }
}

interface CollegesRouteChildren {
  CollegesSlugRoute: typeof CollegesSlugRoute
  CollegesIndexRoute: typeof CollegesIndexRoute
}

const CollegesRouteChildren: CollegesRouteChildren = {
  CollegesSlugRoute: CollegesSlugRoute,
  CollegesIndexRoute: CollegesIndexRoute,
}

const CollegesRouteWithChildren = CollegesRoute._addFileChildren(
  CollegesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollegesRoute: CollegesRouteWithChildren,
  CutoffsRoute: CutoffsRoute,
  DashboardRoute: DashboardRoute,
  PredictorRoute: PredictorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
