from enum import Enum

class InstitutionType(str, Enum):
    ENGINEERING = "ENGINEERING"
    ARCHITECTURE = "ARCHITECTURE"
    MEDICAL = "MEDICAL"
    DENTAL = "DENTAL"

class ProgramType(str, Enum):
    ENGINEERING = "ENGINEERING"
    ARCHITECTURE = "ARCHITECTURE"
    DESIGN = "DESIGN"
    OTHER = "OTHER"

class RecordStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    DOWNLOADED = "DOWNLOADED"
    PARSED = "PARSED"
    VALIDATED = "VALIDATED"
    PUBLISHED = "PUBLISHED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"

class DocumentType(str, Enum):
    MEMBER_INSTITUTIONS_HTML = "MEMBER_INSTITUTIONS_HTML"
    BE_COLLEGES_HTML = "BE_COLLEGES_HTML"
    COUNSELLING_PORTAL_HTML = "COUNSELLING_PORTAL_HTML"
    CUTOFF_PDF = "CUTOFF_PDF"
    SEAT_MATRIX_PDF = "SEAT_MATRIX_PDF"
    VACANT_SEATS_PDF = "VACANT_SEATS_PDF"
    FEE_STRUCTURE_PDF = "FEE_STRUCTURE_PDF"
    BRANCHES_OFFERED_PDF = "BRANCHES_OFFERED_PDF"
    NOTIFICATION_PDF = "NOTIFICATION_PDF"
    UNKNOWN = "UNKNOWN"
    OTHER = "OTHER"

class SourceAuthorityLevel(str, Enum):
    OFFICIAL_PRIMARY = "OFFICIAL_PRIMARY"
    GOVERNMENT = "GOVERNMENT"
    COLLEGE_OFFICIAL = "COLLEGE_OFFICIAL"
    SECONDARY = "SECONDARY"

class ReviewStatus(str, Enum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FIXED = "FIXED"
    SUPERSEDED = "SUPERSEDED"

class FailureReason(str, Enum):
    VALIDATION_FAILED = "VALIDATION_FAILED"
    CORRUPTED_FILE = "CORRUPTED_FILE"
    CORRUPT_DOCUMENT = "CORRUPTED_FILE"
    SUSPICIOUS_LOW_COUNT = "SUSPICIOUS_LOW_COUNT"
    DOWNLOAD_ERROR = "DOWNLOAD_ERROR"
    DOWNLOAD_FAILED = "DOWNLOAD_ERROR"
    UNKNOWN_DOCUMENT_TYPE = "UNKNOWN_DOCUMENT_TYPE"
    UNSUPPORTED_DOCUMENT_TYPE = "UNKNOWN_DOCUMENT_TYPE"
    SCANNED_PDF = "VALIDATION_FAILED"
    MALFORMED_ROW = "MALFORMED_ROW"
    PARSE_MALFORMED = "MALFORMED_ROW"
    UNHANDLED_ERROR = "UNHANDLED_ERROR"

class ValidationSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class RunStatus(str, Enum):
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
