from enum import Enum

class InstitutionType(str, Enum):
    ENGINEERING = "ENGINEERING"
    ARCHITECTURE = "ARCHITECTURE"
    MEDICAL = "MEDICAL"
    DENTAL = "DENTAL"

class ProgramType(str, Enum):
    ENGINEERING = "ENGINEERING"
    ARCHITECTURE = "ARCHITECTURE"
    DESIGN = "DESIGN"
    OTHER = "OTHER"

class RecordStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    DOWNLOADED = "DOWNLOADED"
    PARSED = "PARSED"
    VALIDATED = "VALIDATED"
    PUBLISHED = "PUBLISHED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"

class DocumentType(str, Enum):
    MEMBER_INSTITUTIONS_HTML = "MEMBER_INSTITUTIONS_HTML"
    BE_COLLEGES_HTML = "BE_COLLEGES_HTML"
    COUNSELLING_PORTAL_HTML = "COUNSELLING_PORTAL_HTML"
    CUTOFF_PDF = "CUTOFF_PDF"
    SEAT_MATRIX_PDF = "SEAT_MATRIX_PDF"
    FEE_STRUCTURE_PDF = "FEE_STRUCTURE_PDF"
    BRANCHES_OFFERED_PDF = "BRANCHES_OFFERED_PDF"
    NOTIFICATION_PDF = "NOTIFICATION_PDF"
    OTHER = "OTHER"

class ValidationSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class RunStatus(str, Enum):
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
